server.port: 8765

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion/**
        - id: test
          uri: lb://currency-conversion
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*), /currency-conversion/${segment}
